#!/usr/bin/env bash
echo Resync in progress...
rm -f iscsi-scst-howto.txt
curl -kL# -o iscsi-scst-howto.txt https://sourceforge.net/p/scst/svn/HEAD/tree/trunk/iscsi-scst/doc/iscsi-scst-howto.txt?format=raw
git commit -a -m "Resync" && git push
echo Done.
